### ISSUE TITLE
Usage of comma makes no sense

### ISSUE THREAD

**Issue by Gabriel-p** [SubhadeepJasu/pebbles#61] opened 2020-06-16 21:17 UTC
![Captura de pantalla de 2020-06-16 18-16-18](https://user-images.githubusercontent.com/6054951/84829071-828bad00-affd-11ea-8062-e3cabb15f8fe.png)

**Comment by SubhadeepJasu** [comment] 2020-06-20 06:43
What region & language settings are you using?

**Comment by Gabriel-p** [comment] 2020-06-20 14:54
![Captura de pantalla de 2020-06-20 11-53-45](https://user-images.githubusercontent.com/6054951/85204728-c8da5800-b2ec-11ea-9330-b2035b1eb64f.png)

**Comment by SubhadeepJasu** [comment] 2020-06-21 04:21
Aaa, I made a fix for it recently. The error should go away once the latest update goes live.

**Comment by SubhadeepJasu** [comment] 2020-06-21 04:22
Duplicate of #44 #45 #56

**Comment by SubhadeepJasu** [comment] 2020-06-24 05:57
Closing for now until the issue pops up again. Fixed in [v1.0.4](https://github.com/SubhadeepJasu/pebbles/releases/tag/v1.0.4)

**Closed by SubhadeepJasu** 2020-06-24 05:57 UTC
Labels: Duplicate
